services:
  - type: web
    name: mad-server
    env: node
    rootDir: .
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter @mad/server... run clean && pnpm --filter @mad/server... build
    startCommand: node apps/server/dist/apps/server/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
