// scripts/governance/rules/documentation.rules.ts
import { RuleDefinition } from '../core/types';

export const docRules: RuleDefinition[] = [
  {
    id: 'VAL-DOC-001',
    name: 'Local Workstation Path Detection',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    owner: 'Architecture Review Board',
    version: '2.0.0',
    documentationLink: 'AGENTS.md#permanent-link-strategy',
  },
  {
    id: 'VAL-DOC-002',
    name: 'Absolute Local Filesystem Path Detection',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    owner: 'Architecture Review Board',
    version: '2.0.0',
    documentationLink: 'AGENTS.md#permanent-link-strategy',
  },
  {
    id: 'VAL-DOC-003',
    name: 'Broken Link Target Detection',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    owner: 'Architecture Review Board',
    version: '2.0.0',
    documentationLink: 'AGENTS.md#universal-rules-apply-to-every-markdown-file',
  },
  {
    id: 'VAL-DOC-004',
    name: 'Case-Sensitive Filename Casing Detection',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    owner: 'Architecture Review Board',
    version: '2.0.0',
    documentationLink: 'AGENTS.md#production-documentation',
  },
  {
    id: 'VAL-DOC-005',
    name: 'Secret & Credential Detection',
    category: 'SECURITY',
    severity: 'CRITICAL',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN', // Staged rollout: Warning by default
    owner: 'Security Guild',
    version: '2.0.0',
    documentationLink: 'AGENTS.md#universal-rules-apply-to-every-markdown-file',
  },
  {
    id: 'VAL-DOC-006',
    name: 'Duplicate Document Detection',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 0.9,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN', // Staged rollout: Warning by default
    owner: 'Architecture Review Board',
    version: '2.0.0',
    documentationLink: 'AGENTS.md#duplicate-code-prevention',
  },
  {
    id: 'VAL-DOC-007',
    name: 'Reachability-Based Orphan Detection',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN', // Staged rollout: Warning by default
    owner: 'Architecture Review Board',
    version: '2.0.0',
    documentationLink: 'AGENTS.md#orphan-prevention-policy',
  },
  {
    id: 'VAL-DOC-008',
    name: 'Document Lifecycle & Classification Validation',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    owner: 'Architecture Review Board',
    version: '2.0.0',
    documentationLink: 'AGENTS.md#documentation-lifecycle',
  },
  {
    id: 'Duplicate Governance Policy',
    name: 'Duplicate Governance Policy',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing Document Owner',
    name: 'Missing Document Owner',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Orphaned Documentation',
    name: 'Orphaned Documentation',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'SSOT Owner Inconsistency',
    name: 'SSOT Owner Inconsistency',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing Review Date',
    name: 'Missing Review Date',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Invalid Metadata Date Format',
    name: 'Invalid Metadata Date Format',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Outdated Documentation',
    name: 'Outdated Documentation',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Broken Link Target',
    name: 'Broken Link Target',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Broken Reference Link',
    name: 'Broken Reference Link',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Broken Link Anchor',
    name: 'Broken Link Anchor',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Architecture Review Board',
    version: '1.0.0',
    documentationLink: 'AGENTS.md',
  },
];
