// scripts/governance/rules/ui.rules.ts
import { RuleDefinition } from '../core/types';

export const uiRules: RuleDefinition[] = [
  {
    id: 'VAL-UI-001',
    name: 'Modal Backdrop Consistency',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#modal-governance',
  },
  {
    id: 'VAL-UI-002',
    name: 'Shared Modal Component Usage',
    category: 'UI',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#modal-governance',
  },
  {
    id: 'VAL-UI-003',
    name: 'Modal Accessibility Semantics',
    category: 'ACCESSIBILITY',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#accessibility-governance',
  },
  {
    id: 'VAL-UI-004',
    name: 'Table abstraction check',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.9,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-UI-005',
    name: 'Button styling check',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.85,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#buttons',
  },
  {
    id: 'VAL-UI-006',
    name: 'Field layout wrapper check',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-UI-007',
    name: 'Design Token Usage / Hardcoded Colors',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#design-tokens',
  },
  {
    id: 'VAL-UI-008',
    name: 'Heading Hierarchy',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#typography',
  },
  {
    id: 'VAL-UI-009',
    name: 'Interactive Element Touch Target',
    category: 'ACCESSIBILITY',
    severity: 'WARNING',
    confidence: 0.9,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#accessibility',
  },
  {
    id: 'VAL-UI-010',
    name: 'Shared Component Enforcement',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#component-reuse',
  },
  {
    id: 'VAL-UI-011',
    name: 'Duplicate Component Layout',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.90,
    defaultLifecycle: 'NEW',
    ciPolicy: 'INFO_ONLY',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#duplicate-code-prevention',
  },
  {
    id: 'VAL-UI-012',
    name: 'Dead Component',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'INFO_ONLY',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-013',
    name: 'Dead Hook',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'INFO_ONLY',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-014',
    name: 'Dead Utility File',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'INFO_ONLY',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-015',
    name: 'Dead Asset (Image/Icon)',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'INFO_ONLY',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-016',
    name: 'Dead Style File',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'INFO_ONLY',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-017',
    name: 'Safe Delete Verification',
    category: 'UI',
    severity: 'INFO',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'INFO_ONLY',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-018',
    name: 'Possible Unreachable Route',
    category: 'UI',
    severity: 'INFO',
    confidence: 0.80,
    defaultLifecycle: 'NEW',
    ciPolicy: 'INFO_ONLY',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-019',
    name: 'Duplicate File Contents',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.90,
    defaultLifecycle: 'NEW',
    ciPolicy: 'INFO_ONLY',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#duplicate-code-prevention',
  },
];
