// scripts/governance/rules/ui.rules.ts
import { RuleDefinition } from '../core/types';

export const uiRules: RuleDefinition[] = [
  {
    id: 'VAL-UI-001',
    name: 'Modal Backdrop Consistency',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#modal-governance',
  },
  {
    id: 'VAL-UI-002',
    name: 'Shared Modal Component Usage',
    category: 'UI',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#modal-governance',
  },
  {
    id: 'VAL-UI-003',
    name: 'Modal Accessibility Semantics',
    category: 'ACCESSIBILITY',
    severity: 'ERROR',
    confidence: 1.0,
    defaultLifecycle: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#accessibility-governance',
  },
  {
    id: 'VAL-UI-004',
    name: 'Table abstraction check',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.9,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-UI-005',
    name: 'Button styling check',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.85,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'UI UX Guild',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#buttons',
  },
  {
    id: 'VAL-UI-006',
    name: 'Field layout wrapper check',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    defaultLifecycle: 'NEW',
    ciPolicy: 'WARN',
    owner: 'Platform Team',
    version: '1.0.0',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
];
