export { magicLinkHtml } from "./templates/magic-link";
export type { MagicLinkEmailData } from "./templates/magic-link";
export { fullRefundHtml } from "./templates/full-refund";
export type { FullRefundData } from "./templates/full-refund";
export { partialRefundHtml } from "./templates/partial-refund";
export type { PartialRefundData } from "./templates/partial-refund";
export { paymentFailureHtml } from "./templates/payment-failure";
export type { PaymentFailureData } from "./templates/payment-failure";
export { eventCancellationHtml } from "./templates/event-cancellation";
export type { EventCancellationData } from "./templates/event-cancellation";
