// scripts/governance/rules/metadata/ACCESSIBILITY.ts
import { RuleDefinition } from '../types';

export const accessibilityRules: RuleDefinition[] = [
  {
    id: 'VAL-UI-003',
    name: 'Modal Accessibility Semantics',
    description: 'Enforces standard accessibility properties (aria-labelledby, role="dialog") on modals.',
    category: 'ACCESSIBILITY',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-003.md',
    remediation: 'Ensure the Modal/Dialog containers have appropriate role and aria attribute properties.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['accessibility', 'modal', 'semantics'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#accessibility-governance',
  },
  {
    id: 'VAL-UI-009',
    name: 'Interactive Element Touch Target',
    description: 'Enforces minimum touch target size of 44px for interactive components.',
    category: 'ACCESSIBILITY',
    severity: 'WARNING',
    confidence: 0.9,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-009.md',
    remediation: 'Ensure buttons and links have a minimum clickable area of 44px by 44px.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['accessibility', 'touch-target'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#accessibility',
  },
];
