// scripts/governance/rules/metadata/ARCHITECTURE.ts
import { RuleDefinition } from '../types';

export const architectureRules: RuleDefinition[] = [
  {
    id: 'VAL-ARC-001',
    name: 'Observability Isolation',
    description: 'Enforces that only standard logger and observability wrappers are used, blocking raw console outputs.',
    category: 'ARCHITECTURE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-ARC-001.md',
    remediation: 'Replace console.log/console.error with the standard Logger service calls.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'observability'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#code-quality-rules',
  },
  {
    id: 'VAL-ARC-002',
    name: 'DTO Governance - Direct Axios Import Block',
    description: 'Blocks direct imports of Axios inside application controllers to enforce API contract boundaries.',
    category: 'ARCHITECTURE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-ARC-002.md',
    remediation: 'Use the standardized API fetch client wrappers instead of importing Axios directly.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'api', 'dto'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#frontend-backend-contract-governance',
  },
  {
    id: 'VAL-ARC-003',
    name: 'App Router Layout Safety',
    description: 'Verifies Next.js app router layout structure and limits nesting complexity.',
    category: 'ARCHITECTURE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-ARC-003.md',
    remediation: 'Restructure layout layers to prevent excessive route nesting.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'nextjs', 'routing'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#file-size-governance',
  },
  {
    id: 'VAL-ARC-004',
    name: 'Validation Drift Prevention',
    description: 'Validates that Zod validation schemas are shared and in sync between backend and frontend contracts.',
    category: 'ARCHITECTURE',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-ARC-004.md',
    remediation: 'Refactor validation schemas into @mad/validations package.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'validation', 'zod'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#frontend-backend-contract-governance',
  },
];
