// scripts/governance/rules/metadata/ARCHITECTURE.ts
import { RuleDefinition } from '../types';

export const architectureRules: RuleDefinition[] = [
  {
    id: 'VAL-ARC-001',
    name: 'Observability Isolation',
    description: 'Enforces that only standard logger and observability wrappers are used, blocking raw console outputs.',
    category: 'ARCHITECTURE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-ARC-001.md',
    remediation: 'Replace console.log/console.error with the standard Logger service calls.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'observability'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#code-quality-rules',
  },
  {
    id: 'VAL-ARC-002',
    name: 'DTO Governance - Direct Axios Import Block',
    description: 'Blocks direct imports of Axios inside application controllers to enforce API contract boundaries.',
    category: 'ARCHITECTURE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-ARC-002.md',
    remediation: 'Use the standardized API fetch client wrappers instead of importing Axios directly.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'api', 'dto'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#frontend-backend-contract-governance',
  },
  {
    id: 'VAL-ARC-003',
    name: 'App Router Layout Safety',
    description: 'Verifies Next.js app router layout structure and limits nesting complexity.',
    category: 'ARCHITECTURE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-ARC-003.md',
    remediation: 'Restructure layout layers to prevent excessive route nesting.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'nextjs', 'routing'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#file-size-governance',
  },
  {
    id: 'VAL-ARC-004',
    name: 'Validation Drift Prevention',
    description: 'Validates that Zod validation schemas are shared and in sync between backend and frontend contracts.',
    category: 'ARCHITECTURE',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-ARC-004.md',
    remediation: 'Refactor validation schemas into @mad/validations package.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'validation', 'zod'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#frontend-backend-contract-governance',
  },
  {
    id: 'VAL-ARC-005',
    name: 'Circular Import Detection (Critical)',
    description: 'Detects cross-package or runtime-initialization import cycles that cause module resolution failures.',
    category: 'ARCHITECTURE',
    severity: 'CRITICAL',
    confidence: 0.95,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-ARC-005.md',
    remediation: 'Break the import cycle by extracting shared logic to a dependency-free module.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'imports', 'cycles', 'critical'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-ARC-005b',
    name: 'Circular Import Detection (Warning)',
    description: 'Detects intra-package feature-folder or test-only import cycles that should be refactored.',
    category: 'ARCHITECTURE',
    severity: 'WARNING',
    confidence: 0.85,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-ARC-005.md',
    remediation: 'Refactor the internal import graph to eliminate the cycle.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'imports', 'cycles', 'warning'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-ARC-006',
    name: 'Deep Import Restriction',
    description: 'Blocks imports that pierce @mad/* package internals (/src/ paths), enforcing public barrel API boundaries across the monorepo.',
    category: 'ARCHITECTURE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-ARC-006.md',
    remediation: 'Import from the package public barrel (e.g. @mad/ui) instead of its internal src/ paths.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'imports', 'boundaries'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-ARC-007',
    name: 'Barrel File API Surface Governance',
    description: 'Validates package index.ts barrel files for duplicate exports, internal path leaks, empty barrels, and circular re-exports.',
    category: 'ARCHITECTURE',
    severity: 'WARNING',
    confidence: 0.9,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-ARC-007.md',
    remediation: 'Remove duplicate, conflicting, or internal exports from the package barrel file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['architecture', 'barrel', 'exports', 'api-surface'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
];
