// scripts/governance/rules/metadata/CODE_QUALITY.ts
import { RuleDefinition } from '../types';

export const codeQualityRules: RuleDefinition[] = [
  {
    id: 'VAL-QUAL-001',
    name: 'UI Component File Size Limit',
    description: 'Enforces maximum line count (300 lines) for UI components and page views to prevent God Components.',
    category: 'CODE_QUALITY',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-QUAL-001.md',
    remediation: 'Decompose monolithic component into smaller sub-components, custom hooks, and utility files.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['code-quality', 'file-size', 'components', 'maintainability'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#file-size-governance',
  },
  {
    id: 'VAL-QUAL-002',
    name: 'Custom Hook File Size Limit',
    description: 'Enforces maximum line count (250 lines) for React custom hooks to prevent bloated state machines.',
    category: 'CODE_QUALITY',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-QUAL-002.md',
    remediation: 'Split complex hook logic into smaller dedicated hooks or domain utility functions.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['code-quality', 'file-size', 'hooks', 'react'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#file-size-governance',
  },
  {
    id: 'VAL-QUAL-003',
    name: 'Controller File Size Limit',
    description: 'Enforces maximum line count (200 lines) for API controllers to ensure single-responsibility routing.',
    category: 'CODE_QUALITY',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-QUAL-003.md',
    remediation: 'Decompose controller by sub-lifecycle or action domain (e.g. create, query, webhook, refund).',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['code-quality', 'file-size', 'controllers', 'backend'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#file-size-governance',
  },
  {
    id: 'VAL-QUAL-004',
    name: 'Backend Service File Size Limit',
    description: 'Enforces maximum line count (500 lines) for backend services to prevent domain logic monoliths.',
    category: 'CODE_QUALITY',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-QUAL-004.md',
    remediation: 'Extract domain sub-services and business helpers into dedicated service files.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['code-quality', 'file-size', 'services', 'backend'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#file-size-governance',
  },
  {
    id: 'VAL-QUAL-005',
    name: 'Schema File Size Limit',
    description: 'Enforces maximum line count (300 lines) for Mongoose and validation schemas.',
    category: 'CODE_QUALITY',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-QUAL-005.md',
    remediation: 'Split complex nested schemas into sub-schemas or modular validation files.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['code-quality', 'file-size', 'schemas'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#file-size-governance',
  },
  {
    id: 'VAL-QUAL-006',
    name: 'Test Suite Partitioning Limit',
    description: 'Enforces maximum line count (800 lines) for test files to mandate behavior/lifecycle partitioning.',
    category: 'CODE_QUALITY',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-QUAL-006.md',
    remediation: 'Split test suite by behavior or method (e.g. service.intent.test.ts, service.webhook.test.ts).',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['code-quality', 'file-size', 'testing'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#file-size-governance',
  },
  {
    id: 'VAL-QUAL-007',
    name: 'Function Cyclomatic Complexity Limit',
    description: 'Flags functions with cyclomatic complexity exceeding 15 branches/decision points.',
    category: 'CODE_QUALITY',
    severity: 'WARNING',
    confidence: 0.9,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-QUAL-007.md',
    remediation: 'Simplify branching logic, use lookup tables, or extract helper functions.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['code-quality', 'complexity', 'maintainability'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#code-cleanliness',
  },
  {
    id: 'VAL-QUAL-008',
    name: 'Single Responsibility & State Overload Limit',
    description: 'Flags React components containing more than 10 useState/useEffect declarations.',
    category: 'CODE_QUALITY',
    severity: 'WARNING',
    confidence: 0.9,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-QUAL-008.md',
    remediation: 'Consolidate component state into a custom hook or reducer.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['code-quality', 'react', 'state-management', 'single-responsibility'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#single-source-of-truth',
  },
];
