// scripts/governance/rules/metadata/DOCUMENTATION.ts
import { RuleDefinition } from '../types';

export const docRules: RuleDefinition[] = [
  {
    id: 'Malformed ATX Heading',
    name: 'Malformed ATX Heading',
    description: 'Detects ATX headings that do not have a space after the header characters (e.g. #Heading instead of # Heading).',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MALFORMED_ATX_HEADING.md',
    remediation: 'Insert a space after the heading marker characters.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['markdown', 'formatting'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Duplicate Heading',
    name: 'Duplicate Heading',
    description: 'Detects identical headings within the same markdown document.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/DUPLICATE_HEADING.md',
    remediation: 'Ensure all heading texts in a single document are unique to allow valid anchors.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['markdown', 'hygiene'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Unclosed Fenced Code Block',
    name: 'Unclosed Fenced Code Block',
    description: 'Detects fenced code blocks that are missing their closing triple backtick markers.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/UNCLOSED_CODE_BLOCK.md',
    remediation: 'Add a closing triple backtick on a new line after the code block contents.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['markdown', 'syntax'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Malformed Table Column Count',
    name: 'Malformed Table Column Count',
    description: 'Checks if table rows have a different number of pipe delimiters than the table header.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MALFORMED_TABLE.md',
    remediation: 'Adjust table cells/delimiters to match header column count.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['markdown', 'table'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing SSOT Document',
    name: 'Missing SSOT Document',
    description: 'Verifies that a mandatory Single Source of Truth document exists in the repository.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/MISSING_SSOT.md',
    remediation: 'Create the missing SSOT document following the repository template.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ssot', 'governance'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing SSOT Owner',
    name: 'Missing SSOT Owner',
    description: 'Checks for mandatory owner field in SSOT document metadata block.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_SSOT_OWNER.md',
    remediation: 'Specify the owner role/group in the frontmatter of the SSOT file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ssot', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing SSOT Date',
    name: 'Missing SSOT Date',
    description: 'Checks for mandatory update/review date field in SSOT frontmatter metadata.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_SSOT_DATE.md',
    remediation: 'Add a Last Updated/Review Date to the frontmatter metadata.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ssot', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Invalid SSOT Date Format',
    name: 'Invalid SSOT Date Format',
    description: 'Validates format of metadata date field (expects YYYY-MM-DD).',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/INVALID_SSOT_DATE.md',
    remediation: 'Format the date as YYYY-MM-DD.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ssot', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing SSOT Metadata Field',
    name: 'Missing SSOT Metadata Field',
    description: 'Ensures other required frontmatter metadata fields are not missing.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_SSOT_FIELD.md',
    remediation: 'Populate missing frontmatter metadata fields.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ssot', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing SSOT Metadata',
    name: 'Missing SSOT Metadata',
    description: 'Verifies that a frontmatter block exists at the top of the SSOT file.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_SSOT_METADATA.md',
    remediation: 'Add a valid frontmatter metadata block at the top of the document.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ssot', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing Required Section',
    name: 'Missing Required Section',
    description: 'Verifies presence of mandatory headers in SSOT documents.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_SECTION.md',
    remediation: 'Ensure the document has all mandatory headings.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ssot', 'structure'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Circular Document Dependency',
    name: 'Circular Document Dependency',
    description: 'Checks for circular reference loop in markdown cross-references.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/CIRCULAR_DOC.md',
    remediation: 'Break the circular document dependency loop by refactoring links.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['markdown', 'links'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing SSOT Reference',
    name: 'Missing SSOT Reference',
    description: 'Checks if an SSOT document lacks references from incoming nodes.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_SSOT_REF.md',
    remediation: 'Link to this SSOT document from relevant workspace files.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ssot', 'links'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Unclosed Mermaid Block',
    name: 'Unclosed Mermaid Block',
    description: 'Detects a mermaid code block that has not been terminated.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/UNCLOSED_MERMAID.md',
    remediation: 'Add a closing triple backtick at the end of the mermaid block.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['mermaid', 'syntax'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Empty Mermaid Block',
    name: 'Empty Mermaid Block',
    description: 'Flag empty mermaid code blocks.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/EMPTY_MERMAID.md',
    remediation: 'Populate the diagram block with mermaid code or remove it.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['mermaid', 'syntax'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Invalid Mermaid Diagram Type',
    name: 'Invalid Mermaid Diagram Type',
    description: 'Validates that the mermaid block declares a supported diagram type.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/INVALID_MERMAID_TYPE.md',
    remediation: 'Ensure the first declaration inside the mermaid block is a supported type (e.g. flowchart TD).',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['mermaid', 'syntax'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Malformed Mermaid Quotes',
    name: 'Malformed Mermaid Quotes',
    description: 'Flags unclosed string quotes inside node labels in mermaid syntax.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MALFORMED_MERMAID_QUOTES.md',
    remediation: 'Ensure all string quotes inside node labels are closed.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['mermaid', 'syntax'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Malformed Mermaid Enclosure',
    name: 'Malformed Mermaid Enclosure',
    description: 'Flags unclosed bracket/parenthesis enclosures for node definitions.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MALFORMED_MERMAID_ENCLOSURE.md',
    remediation: 'Ensure all brackets or parentheses enclosing node text are correctly balanced.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['mermaid', 'syntax'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Invalid Mermaid Flowchart Connection',
    name: 'Invalid Mermaid Flowchart Connection',
    description: 'Flags invalid arrow structures (e.g. --> with invalid spacing/syntax).',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/INVALID_MERMAID_CONNECTION.md',
    remediation: 'Correct flowchart connection syntax (e.g., use --> or -.-).',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['mermaid', 'syntax'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing Decisions Directory',
    name: 'Missing Decisions Directory',
    description: 'Checks if docs/decisions directory is missing when indexing ADRs.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/MISSING_ADR_DIR.md',
    remediation: 'Create docs/decisions/ directory.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'structure'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Read Directory Error',
    name: 'Read Directory Error',
    description: 'System error reading ADR directories during scan.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/READ_DIR_ERROR.md',
    remediation: 'Ensure decisions directory has read permissions.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'system'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Invalid ADR Naming',
    name: 'Invalid ADR Naming',
    description: 'Validates that ADR files follow ADR-###-description.md naming rules.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/INVALID_ADR_NAMING.md',
    remediation: 'Rename the file to match the ADR-###-description-kebab-case.md format.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'naming'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Malformed H1 Title',
    name: 'Malformed H1 Title',
    description: 'Checks if ADR first H1 header is malformed or differs from filename description.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MALFORMED_H1.md',
    remediation: 'Align H1 text with ADR number and description.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'header'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing H1 Heading',
    name: 'Missing H1 Heading',
    description: 'Checks if first heading in ADR is an H1.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/MISSING_H1.md',
    remediation: 'Add an H1 heading at the top of the ADR file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'header'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing ADR Status',
    name: 'Missing ADR Status',
    description: 'Validates status field in ADR metadata table block.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_ADR_STATUS.md',
    remediation: 'Add Status to the Metadata table in the ADR.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Invalid ADR Lifecycle Status',
    name: 'Invalid ADR Lifecycle Status',
    description: 'Validates status is one of Proposed, Accepted, Rejected, Superceded, Deprecated.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/INVALID_ADR_STATUS.md',
    remediation: 'Update the ADR Status value to a valid lifecycle state.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing ADR Date',
    name: 'Missing ADR Date',
    description: 'Checks for Date in ADR metadata frontmatter.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_ADR_DATE.md',
    remediation: 'Add Date to the ADR metadata block.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Invalid ADR Date Format',
    name: 'Invalid ADR Date Format',
    description: 'Validates ADR date format is YYYY-MM-DD.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/INVALID_ADR_DATE.md',
    remediation: 'Format date in ADR as YYYY-MM-DD.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing ADR Authors',
    name: 'Missing ADR Authors',
    description: 'Checks for Authors metadata in ADR.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_ADR_AUTHORS.md',
    remediation: 'Add Authors to the ADR metadata block.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing ADR Related Documents',
    name: 'Missing ADR Related Documents',
    description: 'Checks for Related Documents metadata in ADR.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_ADR_DOCS.md',
    remediation: 'Add Related Documents to the ADR metadata block.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing ADR Metadata',
    name: 'Missing ADR Metadata',
    description: 'Ensures the Metadata section heading is present in the ADR.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_ADR_METADATA.md',
    remediation: 'Add a Metadata section to the ADR.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing Template Heading',
    name: 'Missing Template Heading',
    description: 'Validates that the ADR contains all expected template headings.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_ADR_HEADING.md',
    remediation: 'Ensure the ADR has Context, Decision, Consequences, and Future Considerations headings.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'structure'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Duplicate ADR Number',
    name: 'Duplicate ADR Number',
    description: 'Checks if two ADR files share the same index number prefix.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/DUPLICATE_ADR_NUM.md',
    remediation: 'Assign a unique sequential number prefix to the ADR file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'numbering'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'ADR Number Gap',
    name: 'ADR Number Gap',
    description: 'Checks for gaps in ADR numbering sequence.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/ADR_GAP.md',
    remediation: 'Ensure ADR numbers are consecutive.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'numbering'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing ADR Index',
    name: 'Missing ADR Index',
    description: 'Checks for index file ADR_INDEX.md in decisions directory.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/MISSING_ADR_INDEX.md',
    remediation: 'Create the ADR_INDEX.md file in the decisions folder.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'index'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing Index Entry',
    name: 'Missing Index Entry',
    description: 'Checks if an existing ADR is unregistered in index.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/MISSING_INDEX_ENTRY.md',
    remediation: 'Register the ADR entry inside the ADR_INDEX.md table.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'index'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Index Title Mismatch',
    name: 'Index Title Mismatch',
    description: 'Checks if index table title matches ADR H1 title.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/ADR_TITLE_MISMATCH.md',
    remediation: 'Update index table title to match the ADR heading.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'index'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Index Status Mismatch',
    name: 'Index Status Mismatch',
    description: 'Checks if index table status matches ADR status.',
    category: 'DOCUMENTATION',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/ADR_STATUS_MISMATCH.md',
    remediation: 'Update index status to match the ADR metadata status.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'index'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Orphan Index Entry',
    name: 'Orphan Index Entry',
    description: 'Checks if index registers an ADR that does not exist on disk.',
    category: 'DOCUMENTATION',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Documentation Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/ORPHAN_INDEX.md',
    remediation: 'Remove the orphaned entry from the index table.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['adr', 'index'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
];
