// scripts/governance/rules/metadata/HYGIENE.ts
import { RuleDefinition } from '../types';

export const hygieneRules: RuleDefinition[] = [
  {
    id: 'VAL-DOC-001',
    name: 'Local Workstation Path Detection',
    description: 'Detects workstation-specific local folder paths (like workstation file:/// paths).',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-DOC-001.md',
    remediation: 'Replace workstation absolute paths with relative workspace links.',
    supportsAutofix: false,
    version: '2.0.0',
    introducedVersion: '2.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'documentation', 'workstation'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#permanent-link-strategy',
  },
  {
    id: 'VAL-DOC-002',
    name: 'Absolute Local Filesystem Path Detection',
    description: 'Enforces relative links instead of absolute root-relative filesystem paths.',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-DOC-002.md',
    remediation: 'Change absolute paths to relative paths.',
    supportsAutofix: false,
    version: '2.0.0',
    introducedVersion: '2.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'documentation'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#permanent-link-strategy',
  },
  {
    id: 'VAL-DOC-003',
    name: 'Broken Link Target Detection',
    description: 'Validates target filesystem paths for all markdown links.',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-DOC-003.md',
    remediation: 'Correct the broken target path to point to a valid file in the workspace.',
    supportsAutofix: false,
    version: '2.0.0',
    introducedVersion: '2.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'documentation', 'links'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#universal-rules-apply-to-every-markdown-file',
  },
  {
    id: 'VAL-DOC-004',
    name: 'Case-Sensitive Filename Casing Detection',
    description: 'Ensures link targets match the exact case of filenames on disk.',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-DOC-004.md',
    remediation: 'Update link capitalization to match the file exactly.',
    supportsAutofix: false,
    version: '2.0.0',
    introducedVersion: '2.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'documentation', 'casing'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#production-documentation',
  },
  {
    id: 'VAL-DOC-006',
    name: 'Duplicate Document Detection',
    description: 'Identifies documents sharing identical structural content.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 0.9,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-DOC-006.md',
    remediation: 'Consolidate duplicate document files.',
    supportsAutofix: false,
    version: '2.0.0',
    introducedVersion: '2.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'documentation', 'duplicate'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#duplicate-code-prevention',
  },
  {
    id: 'VAL-DOC-007',
    name: 'Reachability-Based Orphan Detection',
    description: 'Detects files that are completely orphaned from doc trees.',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-DOC-007.md',
    remediation: 'Link the orphan doc from active pages.',
    supportsAutofix: false,
    version: '2.0.0',
    introducedVersion: '2.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'documentation', 'orphans'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#orphan-prevention-policy',
  },
  {
    id: 'VAL-DOC-008',
    name: 'Document Lifecycle & Classification Validation',
    description: 'Checks metadata schema versions and lifecycle classifications.',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-DOC-008.md',
    remediation: 'Fill in the correct frontmatter tags for document lifecycle classification.',
    supportsAutofix: false,
    version: '2.0.0',
    introducedVersion: '2.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'documentation', 'lifecycle'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#documentation-lifecycle',
  },
  {
    id: 'Duplicate Governance Policy',
    name: 'Duplicate Governance Policy',
    description: 'Checks for duplicates in declared governance policies.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/DUPLICATE_POLICY.md',
    remediation: 'Resolve duplicate policy declarations.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'governance'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing Document Owner',
    name: 'Missing Document Owner',
    description: 'Checks for missing Owner metadata field in repository files.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_DOC_OWNER.md',
    remediation: 'Specify the Owner metadata header.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Orphaned Documentation',
    name: 'Orphaned Documentation',
    description: 'Checks for documentation files with no incoming links.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/ORPHANED_DOC.md',
    remediation: 'Add incoming links from other markdown files.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'links'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'SSOT Owner Inconsistency',
    name: 'SSOT Owner Inconsistency',
    description: 'Verifies owner matches standard role mappings.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/SSOT_OWNER_INCONSISTENCY.md',
    remediation: 'Update owner to match established role registry.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Missing Review Date',
    name: 'Missing Review Date',
    description: 'Checks for missing review cycle dates.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/MISSING_REVIEW_DATE.md',
    remediation: 'Provide a valid Last Updated or Next Review date.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Invalid Metadata Date Format',
    name: 'Invalid Metadata Date Format',
    description: 'Ensures all metadata dates are properly formatted.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/INVALID_METADATA_DATE.md',
    remediation: 'Use YYYY-MM-DD format for date metadata.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'metadata'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Outdated Documentation',
    name: 'Outdated Documentation',
    description: 'Checks for documents past their review cycle expiration.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/OUTDATED_DOC.md',
    remediation: 'Review the document and update the review cycle timestamp.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'metadata', 'outdated'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Broken Link Target',
    name: 'Broken Link Target',
    description: 'Validates target paths for all links.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/BROKEN_LINK_TARGET.md',
    remediation: 'Fix the target link path.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'links'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Broken Reference Link',
    name: 'Broken Reference Link',
    description: 'Checks for invalid markdown reference-style links.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/BROKEN_REF_LINK.md',
    remediation: 'Ensure reference-style links match defined link targets.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'links'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'Broken Link Anchor',
    name: 'Broken Link Anchor',
    description: 'Checks for invalid hash anchors in workspace links.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Architecture Review Board',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/BROKEN_ANCHOR.md',
    remediation: 'Verify and align headings with link anchors.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'links'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'AST-PARSE-WARNING',
    name: 'AST Parsing Warning',
    description: 'Parser warning when processing code files for syntax analysis.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/AST_PARSE_WARNING.md',
    remediation: 'Review and fix the syntax error/warning in the target file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'syntax', 'ast'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'VAL-HYG-001',
    name: 'Import Ordering & Grouping',
    description: 'Ensures imports are ordered alphabetically and grouped: node-builtins, modules, workspace, relative, side-effects.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-HYG-001.md',
    remediation: 'Group and order imports alphabetically within groups, separated by a blank line.',
    supportsAutofix: true,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'imports'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'VAL-HYG-002',
    name: 'Duplicate Imports Detection',
    description: 'Detects duplicate import declarations from the same module path.',
    category: 'HYGIENE',
    severity: 'ERROR',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-HYG-002.md',
    remediation: 'Merge duplicate import declarations into a single statement.',
    supportsAutofix: true,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'imports'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'VAL-HYG-003',
    name: 'Type Imports Enforcement',
    description: 'Enforces type-only specifiers to be imported using the type keyword.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-HYG-003.md',
    remediation: 'Import type-only files using the type keyword.',
    supportsAutofix: true,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'imports', 'types'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'VAL-HYG-004',
    name: 'Trailing Whitespace Detection',
    description: 'Detects trailing whitespace characters at the end of lines.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-HYG-004.md',
    remediation: 'Trim trailing spaces and tabs from the end of all lines.',
    supportsAutofix: true,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'whitespace'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'VAL-HYG-005',
    name: 'EOF Newline Enforcement',
    description: 'Verifies that files terminate with a single trailing newline.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-HYG-005.md',
    remediation: 'Ensure the file ends with a single trailing newline character.',
    supportsAutofix: true,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'formatting'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'VAL-HYG-006',
    name: 'Excessive Blank Lines Collapse',
    description: 'Flags three or more consecutive blank lines in a file.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-HYG-006.md',
    remediation: 'Collapse consecutive blank lines down to a maximum of one.',
    supportsAutofix: true,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'formatting'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md',
  },
  {
    id: 'VAL-HYG-007',
    name: 'TODO Inventory Consistency',
    description: 'Detects undocumented TODO/FIXME/HACK/XXX comments that lack a ticket reference or owner attribution.',
    category: 'HYGIENE',
    severity: 'WARNING',
    confidence: 0.85,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-HYG-007.md',
    remediation: 'Add a ticket reference (e.g. // TODO(#123)) or owner attribution (// TODO(@owner)) to the comment.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'todo', 'debt'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-HYG-008',
    name: 'Protected Branch Modification',
    description: 'Detects if files are modified on protected branches (develop, live, main, master) without a task branch.',
    category: 'HYGIENE',
    severity: 'CRITICAL',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-HYG-008.md',
    remediation: 'Stash changes, checkout a task branch, and pop stashed changes.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['hygiene', 'git', 'branch-safety'],
    governanceSource: {
      document: 'AGENTS.md',
      section: 'BRANCH SAFETY',
      standard: 'Git Workflow',
    },
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#branch-safety',
  },
];
