// scripts/governance/rules/metadata/PERFORMANCE.ts
import { RuleDefinition } from '../types';

export const performanceRules: RuleDefinition[] = [
  {
    id: 'VAL-PFM-001',
    name: 'Optimize Font Loading',
    description: 'Enforces usage of local fonts or specific optimization flags to avoid rendering layout shifts.',
    category: 'PERFORMANCE',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-PFM-001.md',
    remediation: 'Configure font-display and preloading for local fonts.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['performance', 'fonts', 'layout-shift'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#code-quality-rules',
  },
  {
    id: 'VAL-PFM-002',
    name: 'Avoid Render-Blocking Imports',
    description: 'Prevents synchronous scripts and blocking imports in index templates.',
    category: 'PERFORMANCE',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-PFM-002.md',
    remediation: 'Add defer or async attributes to script elements, and load non-critical resources asynchronously.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['performance', 'imports'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#code-quality-rules',
  },
];
