// scripts/governance/rules/metadata/SECURITY.ts
import { RuleDefinition } from '../types';

export const securityRules: RuleDefinition[] = [
  {
    id: 'VAL-SEC-001',
    name: 'Secure Upload Handling',
    description: 'Enforces strict validation, sanitization, and size checking on file uploads.',
    category: 'SECURITY',
    severity: 'CRITICAL',
    confidence: 1.0,
    owner: 'Security Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-SEC-001.md',
    remediation: 'Implement file mime-type and magic bytes validation, limit payload size, and store outside public path.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['security', 'upload'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#high-risk-areas',
  },
  {
    id: 'VAL-SEC-002',
    name: 'RBAC Authorization check',
    description: 'Ensures proper role checks exist before API controller routes execution.',
    category: 'SECURITY',
    severity: 'CRITICAL',
    confidence: 1.0,
    owner: 'Security Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-SEC-002.md',
    remediation: 'Wrap API endpoints with standard RBAC check middleware.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['security', 'rbac', 'authorization'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#high-risk-areas',
  },
  {
    id: 'VAL-DOC-005',
    name: 'Secret & Credential Detection',
    description: 'Scans markdown documentation files for hardcoded API keys, secrets, or certificates.',
    category: 'SECURITY',
    severity: 'CRITICAL',
    confidence: 1.0,
    owner: 'Security Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-DOC-005.md',
    remediation: 'Remove the hardcoded secret from documentation. Use environment configurations.',
    supportsAutofix: false,
    version: '2.0.0',
    introducedVersion: '2.0.0',
    status: 'ACTIVE',
    tags: ['security', 'secrets', 'documentation'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#universal-rules-apply-to-every-markdown-file',
  },
];
