// scripts/governance/rules/metadata/UI.ts
import { RuleDefinition } from '../types';

export const uiRules: RuleDefinition[] = [
  {
    id: 'VAL-UI-001',
    name: 'Modal Backdrop Consistency',
    description: 'Enforces standard styling for modal overlay backdrop filters.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-001.md',
    remediation: 'Ensure modal overlays use the standardized backdrop filter tokens.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'modal', 'style'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#modal-governance',
  },
  {
    id: 'VAL-UI-002',
    name: 'Shared Modal Component Usage',
    description: 'Checks for raw modal implementations and enforces standard dialog wrap.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-002.md',
    remediation: 'Use the shared Dialog or Modal components instead of direct HTML div dialog overlays.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'modal', 'components'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#modal-governance',
  },
  {
    id: 'VAL-UI-004',
    name: 'Table abstraction check',
    description: 'Enforces standard Table abstraction wrappers instead of raw HTML tables.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.9,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-004.md',
    remediation: 'Use Table components from @mad/ui instead of raw <table> tags.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'table', 'components'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-UI-005',
    name: 'Button styling check',
    description: 'Enforces Button component usage and prevents raw custom buttons.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.85,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-005.md',
    remediation: 'Use standard Button components from @mad/ui.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'button', 'components'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#buttons',
  },
  {
    id: 'VAL-UI-006',
    name: 'Field layout wrapper check',
    description: 'Ensures standard wrapper components are utilized for form inputs.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-006.md',
    remediation: 'Wrap inputs in the standardized Field or FormRow components.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'forms'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-UI-007',
    name: 'Design Token Usage / Hardcoded Colors',
    description: 'Detects hardcoded color strings in CSS/styled-components files.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-007.md',
    remediation: 'Replace hardcoded hex/rgb/named colors with standardized design token variables.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'tokens', 'colors'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#design-tokens',
  },
  {
    id: 'VAL-UI-008',
    name: 'Heading Hierarchy',
    description: 'Validates that heading levels (h1-h6) form a consistent nested structure.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-008.md',
    remediation: 'Adjust heading levels so they nest correctly without skipping levels.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'seo', 'accessibility'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#typography',
  },
  {
    id: 'VAL-UI-010',
    name: 'Shared Component Enforcement',
    description: 'Blocks raw HTML buttons and tables in favor of standardized UI components.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-010.md',
    remediation: 'Replace raw button or table tags with Button or Table components.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'components'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#component-reuse',
  },
  {
    id: 'VAL-UI-011',
    name: 'Duplicate Component Layout',
    description: 'Detects duplicate JSX layout/structure across components.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.90,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-011.md',
    remediation: 'Extract duplicate layouts into shared reusable components.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'duplicate', 'hygiene'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#duplicate-code-prevention',
  },
  {
    id: 'VAL-UI-012',
    name: 'Dead Component',
    description: 'Identifies component files that are not imported anywhere in active projects.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-012.md',
    remediation: 'Remove the dead component file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-013',
    name: 'Dead Hook',
    description: 'Identifies custom hooks that are not imported or called.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-013.md',
    remediation: 'Remove the unused custom hook.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-014',
    name: 'Dead Utility File',
    description: 'Identifies utility and helper code files that are not imported.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-014.md',
    remediation: 'Remove the unused utility file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-015',
    name: 'Dead Asset (Image/Icon)',
    description: 'Identifies image and asset files that are not referenced in the code.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-015.md',
    remediation: 'Delete the unused image/icon asset file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code', 'assets'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-016',
    name: 'Dead Style File',
    description: 'Identifies css/scss files that are not imported anywhere.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-016.md',
    remediation: 'Remove the unused style file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code', 'style'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-017',
    name: 'Safe Delete Verification',
    description: 'Performs dry-run safe delete classification of unreachable files.',
    category: 'UI',
    severity: 'INFO',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-017.md',
    remediation: 'Review safe-delete classification reports before removing files.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-018',
    name: 'Possible Unreachable Route',
    description: 'Detects Next.js page components with no matching Link or navigation references.',
    category: 'UI',
    severity: 'INFO',
    confidence: 0.80,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-018.md',
    remediation: 'Verify if the route is intended to be public, and add link references if needed.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code', 'routing'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-019',
    name: 'Duplicate File Contents',
    description: 'Detects files with identical content hashes.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.90,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-019.md',
    remediation: 'Remove duplicate files and resolve references to a single source.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'duplicate', 'hygiene'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#duplicate-code-prevention',
  },

  // ─── UI-001 Governance Rules (VAL-UI-020 → VAL-UI-025) ────────────────────
  // These rules enforce the MAD UI/UX Governance Standard (UI-001).
  // Source: UI_UX_GOVERNANCE.md
  // Registry: docs/governance/REGISTRY.md
  // ──────────────────────────────────────────────────────────────────────────

  {
    id: 'VAL-UI-020',
    name: 'Alt Text Missing',
    description: 'Detects <img> elements in JSX/TSX that are missing an alt attribute. All informative images must have descriptive alt text; decorative images must use alt="".',
    category: 'UI',
    severity: 'CRITICAL',
    confidence: 0.99,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'FAIL_BUILD',
    documentation: 'docs/governance/rules/VAL-UI-020.md',
    remediation: 'Add alt="[description]" to informative images. Use alt="" for decorative images.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'accessibility', 'images', 'wcag', 'ui-001', 'static-analysis'],
    governanceSource: {
      document: 'UI_UX_GOVERNANCE.md',
      section: '15. Accessibility',
      standard: 'UI-001',
    },
    defaultLifecycle: 'NEW',
    documentationLink: 'UI_UX_GOVERNANCE.md#15-accessibility',
  },
  {
    id: 'VAL-UI-021',
    name: 'Image Missing Dimensions (CLS Risk)',
    description: 'Detects <img> elements missing explicit width and height attributes. Omitting dimensions causes Cumulative Layout Shift (CLS) as the browser cannot reserve space before the image loads.',
    category: 'UI',
    severity: 'HIGH',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-021.md',
    remediation: 'Add width and height attributes matching the intrinsic image dimensions. Use aspect-ratio CSS to maintain proportions.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'performance', 'cls', 'images', 'ui-001', 'static-analysis'],
    governanceSource: {
      document: 'UI_UX_GOVERNANCE.md',
      section: '18. Performance',
      standard: 'UI-001',
    },
    defaultLifecycle: 'NEW',
    documentationLink: 'UI_UX_GOVERNANCE.md#18-performance',
  },
  {
    id: 'VAL-UI-022',
    name: 'Hardcoded Inline Color',
    description: 'Detects hardcoded hex, rgb(), or hsl() color values used directly in JSX style props. All colors must reference design tokens from the shared design system.',
    category: 'UI',
    severity: 'MEDIUM',
    confidence: 0.90,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-022.md',
    remediation: 'Replace hardcoded color values with CSS custom properties or Tailwind token classes defined in DESIGN_SYSTEM.md.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'tokens', 'colors', 'design-system', 'ui-001', 'static-analysis'],
    governanceSource: {
      document: 'UI_UX_GOVERNANCE.md',
      section: '17. Design System Compliance',
      standard: 'UI-001',
    },
    defaultLifecycle: 'NEW',
    documentationLink: 'DESIGN_SYSTEM.md#2-color-tokens',
  },
  {
    id: 'VAL-UI-023',
    name: 'Overflow-X Hidden on Root Container',
    description: 'Detects overflow-x: hidden applied to root-level containers (html, body, or page wrapper divs). This pattern masks horizontal scroll problems instead of fixing them and prevents legitimate sticky positioning.',
    category: 'UI',
    severity: 'HIGH',
    confidence: 0.85,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-023.md',
    remediation: 'Remove overflow-x: hidden from root containers. Fix the underlying layout issue causing horizontal overflow instead.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'responsive', 'overflow', 'layout', 'ui-001', 'static-analysis'],
    governanceSource: {
      document: 'UI_UX_GOVERNANCE.md',
      section: '2. Responsive Design',
      standard: 'UI-001',
    },
    defaultLifecycle: 'NEW',
    documentationLink: 'RESPONSIVE_GUIDELINES.md#8-overflow-rules',
  },
  {
    id: 'VAL-UI-024',
    name: 'Arbitrary Tailwind Spacing',
    description: 'Detects arbitrary spacing values in Tailwind classes (e.g., mt-[17px], p-[13px]) when spacing tokens from the design system should be used instead.',
    category: 'UI',
    severity: 'LOW',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-024.md',
    remediation: 'Replace arbitrary spacing (mt-[17px]) with the nearest spacing token (mt-4 = 16px, mt-5 = 20px). See DESIGN_SYSTEM.md spacing scale.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'tokens', 'spacing', 'tailwind', 'ui-001', 'static-analysis'],
    governanceSource: {
      document: 'UI_UX_GOVERNANCE.md',
      section: '16. Design Consistency',
      standard: 'UI-001',
    },
    defaultLifecycle: 'NEW',
    documentationLink: 'DESIGN_SYSTEM.md#4-spacing-scale',
  },
  {
    id: 'VAL-UI-025',
    name: 'Duplicate Tailwind Utilities',
    description: 'Detects duplicate Tailwind CSS utility classes applied to the same element (e.g., "flex flex", "p-4 p-5"). The last value wins in Tailwind, making the earlier declarations dead code.',
    category: 'UI',
    severity: 'LOW',
    confidence: 0.98,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-025.md',
    remediation: 'Remove the duplicate utility class. Keep only the intended value.',
    supportsAutofix: true,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'tailwind', 'dead-code', 'hygiene', 'ui-001', 'static-analysis'],
    governanceSource: {
      document: 'UI_UX_GOVERNANCE.md',
      section: '16. Design Consistency',
      standard: 'UI-001',
    },
    defaultLifecycle: 'NEW',
    documentationLink: 'UI_UX_GOVERNANCE.md#16-design-consistency',
  },
];
