// scripts/governance/rules/metadata/UI.ts
import { RuleDefinition } from '../types';

export const uiRules: RuleDefinition[] = [
  {
    id: 'VAL-UI-001',
    name: 'Modal Backdrop Consistency',
    description: 'Enforces standard styling for modal overlay backdrop filters.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-001.md',
    remediation: 'Ensure modal overlays use the standardized backdrop filter tokens.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'modal', 'style'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#modal-governance',
  },
  {
    id: 'VAL-UI-002',
    name: 'Shared Modal Component Usage',
    description: 'Checks for raw modal implementations and enforces standard dialog wrap.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-002.md',
    remediation: 'Use the shared Dialog or Modal components instead of direct HTML div dialog overlays.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'modal', 'components'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#modal-governance',
  },
  {
    id: 'VAL-UI-004',
    name: 'Table abstraction check',
    description: 'Enforces standard Table abstraction wrappers instead of raw HTML tables.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.9,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-004.md',
    remediation: 'Use Table components from @mad/ui instead of raw <table> tags.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'table', 'components'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-UI-005',
    name: 'Button styling check',
    description: 'Enforces Button component usage and prevents raw custom buttons.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.85,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-005.md',
    remediation: 'Use standard Button components from @mad/ui.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'button', 'components'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#buttons',
  },
  {
    id: 'VAL-UI-006',
    name: 'Field layout wrapper check',
    description: 'Ensures standard wrapper components are utilized for form inputs.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-006.md',
    remediation: 'Wrap inputs in the standardized Field or FormRow components.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'forms'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#shared-ownership-rule',
  },
  {
    id: 'VAL-UI-007',
    name: 'Design Token Usage / Hardcoded Colors',
    description: 'Detects hardcoded color strings in CSS/styled-components files.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-007.md',
    remediation: 'Replace hardcoded hex/rgb/named colors with standardized design token variables.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'tokens', 'colors'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#design-tokens',
  },
  {
    id: 'VAL-UI-008',
    name: 'Heading Hierarchy',
    description: 'Validates that heading levels (h1-h6) form a consistent nested structure.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-008.md',
    remediation: 'Adjust heading levels so they nest correctly without skipping levels.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'seo', 'accessibility'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#typography',
  },
  {
    id: 'VAL-UI-010',
    name: 'Shared Component Enforcement',
    description: 'Blocks raw HTML buttons and tables in favor of standardized UI components.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.95,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'WARN',
    documentation: 'docs/governance/rules/VAL-UI-010.md',
    remediation: 'Replace raw button or table tags with Button or Table components.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'components'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#component-reuse',
  },
  {
    id: 'VAL-UI-011',
    name: 'Duplicate Component Layout',
    description: 'Detects duplicate JSX layout/structure across components.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.90,
    owner: 'UI UX Guild',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-011.md',
    remediation: 'Extract duplicate layouts into shared reusable components.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'duplicate', 'hygiene'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#duplicate-code-prevention',
  },
  {
    id: 'VAL-UI-012',
    name: 'Dead Component',
    description: 'Identifies component files that are not imported anywhere in active projects.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-012.md',
    remediation: 'Remove the dead component file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-013',
    name: 'Dead Hook',
    description: 'Identifies custom hooks that are not imported or called.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-013.md',
    remediation: 'Remove the unused custom hook.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-014',
    name: 'Dead Utility File',
    description: 'Identifies utility and helper code files that are not imported.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-014.md',
    remediation: 'Remove the unused utility file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-015',
    name: 'Dead Asset (Image/Icon)',
    description: 'Identifies image and asset files that are not referenced in the code.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-015.md',
    remediation: 'Delete the unused image/icon asset file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code', 'assets'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-016',
    name: 'Dead Style File',
    description: 'Identifies css/scss files that are not imported anywhere.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-016.md',
    remediation: 'Remove the unused style file.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code', 'style'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-017',
    name: 'Safe Delete Verification',
    description: 'Performs dry-run safe delete classification of unreachable files.',
    category: 'UI',
    severity: 'INFO',
    confidence: 1.0,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-017.md',
    remediation: 'Review safe-delete classification reports before removing files.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-018',
    name: 'Possible Unreachable Route',
    description: 'Detects Next.js page components with no matching Link or navigation references.',
    category: 'UI',
    severity: 'INFO',
    confidence: 0.80,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-018.md',
    remediation: 'Verify if the route is intended to be public, and add link references if needed.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'dead-code', 'routing'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#dead-code-policy',
  },
  {
    id: 'VAL-UI-019',
    name: 'Duplicate File Contents',
    description: 'Detects files with identical content hashes.',
    category: 'UI',
    severity: 'WARNING',
    confidence: 0.90,
    owner: 'Platform Team',
    defaultStatus: 'NEW',
    ciPolicy: 'INFO_ONLY',
    documentation: 'docs/governance/rules/VAL-UI-019.md',
    remediation: 'Remove duplicate files and resolve references to a single source.',
    supportsAutofix: false,
    version: '1.0.0',
    introducedVersion: '1.0.0',
    status: 'ACTIVE',
    tags: ['ui', 'duplicate', 'hygiene'],
    defaultLifecycle: 'NEW',
    documentationLink: 'AGENTS.md#duplicate-code-prevention',
  },
];
