// scripts/governance/reports/github_reporter.ts

import { writeFileSync } from 'fs';
import { ValidationResult } from '../core/types';

function escapeAnnotationMessage(msg: string): string {
  return msg
    .replace(/%/g, '%25')
    .replace(/\r/g, '%0D')
    .replace(/\n/g, '%0A');
}

export class GitHubActionsReporter {
  /**
   * Log annotations and write step summary to GitHub Actions environment.
   */
  public static report(results: ValidationResult[], reportContent: any): { success: boolean; failureReason?: string } {
    // 1. Gracefully bypass if not running inside GitHub Actions
    if (process.env.GITHUB_ACTIONS !== 'true') {
      return { success: true };
    }

    let totalErrors = 0;
    let totalWarnings = 0;

    // 2. Output annotations for warnings and errors
    for (const res of results) {
      // Formatted errors
      res.errors.forEach(err => {
        totalErrors++;
        const lineField = err.line ? `,line=${err.line}` : '';
        const escapedMsg = escapeAnnotationMessage(err.message);
        console.log(`::error file=${err.file}${lineField},title=[${res.name}] ${err.rule}::${escapedMsg}`);
      });

      // Formatted warnings
      res.warnings.forEach(warn => {
        totalWarnings++;
        const lineField = warn.line ? `,line=${warn.line}` : '';
        const escapedMsg = escapeAnnotationMessage(warn.message);
        console.log(`::warning file=${warn.file}${lineField},title=[${res.name}] ${warn.rule}::${escapedMsg}`);
      });
    }

    const health = reportContent.health || { score: 100, ownershipCompliance: 100, freshnessCompliance: 100, linkageCompliance: 100 };
    const kpis = reportContent.kpis || { brokenLinksCount: 0, missingSsotReferences: 0, adrNumberingInconsistencies: 0, outdatedDocumentsCount: 0, documentationReviewSlaViolations: 0 };

    const healthScore = health.score;

    // 3. Resolve threshold checks
    const maxWarningsEnv = process.env.GOVERNANCE_MAX_WARNINGS;
    const minHealthScoreEnv = process.env.GOVERNANCE_MIN_HEALTH_SCORE;

    const maxWarnings = maxWarningsEnv ? parseInt(maxWarningsEnv, 10) : Infinity;
    const minHealthScore = minHealthScoreEnv ? parseInt(minHealthScoreEnv, 10) : 0;

    let success = true;
    let failureReason = '';

    if (totalErrors > 0) {
      success = false;
      failureReason = 'One or more validators reported critical errors.';
    } else if (totalWarnings > maxWarnings) {
      success = false;
      failureReason = `Total warnings (${totalWarnings}) exceeds the maximum allowed threshold of ${maxWarnings}.`;
    } else if (healthScore < minHealthScore) {
      success = false;
      failureReason = `Repository Health Score (${healthScore}%) is below the minimum required threshold of ${minHealthScore}%.`;
    }

    // 4. Generate step summary markdown
    const summaryFile = process.env.GITHUB_STEP_SUMMARY;
    if (summaryFile) {
      const summaryMarkdown = `
# 🔍 Governance Documentation Audit Summary

| Metric | Target | Result | Status |
| :--- | :--- | :--- | :--- |
| **Audit Outcome** | Passing | ${success ? 'Success' : 'Failure'} | ${success ? '✅' : '❌'} |
| **Health Score** | >= ${minHealthScore}% | ${healthScore}% | ${healthScore >= minHealthScore ? '✅' : '❌'} |
| **Total Errors** | 0 | ${totalErrors} | ${totalErrors === 0 ? '✅' : '❌'} |
| **Total Warnings** | <= ${maxWarnings === Infinity ? 'N/A' : maxWarnings} | ${totalWarnings} | ${maxWarnings === Infinity ? '⚠️' : (totalWarnings <= maxWarnings ? '✅' : '❌')} |
| **Processed Files** | - | ${reportContent.statistics?.totalFilesProcessed || 0} | 📂 |
| **Execution Time** | - | ${reportContent.summary?.totalTimeMs || 0} ms | ⏱️ |

## 📊 Health Breakdown
- 📋 **Ownership Compliance**: ${health.ownershipCompliance}%
- ⏱️ **Freshness Compliance**: ${health.freshnessCompliance}%
- 🔗 **Linkage Compliance**: ${health.linkageCompliance}%

## 🔑 Key Performance Indicators (KPIs)
- 🔗 **Broken Links**: ${kpis.brokenLinksCount}
- 🔄 **Missing SSOT References**: ${kpis.missingSsotReferences}
- 🔢 **ADR Numbering Inconsistencies**: ${kpis.adrNumberingInconsistencies}
- ⏱️ **Outdated Documents**: ${kpis.outdatedDocumentsCount}
- ⚠️ **Documentation SLA Violations**: ${kpis.documentationReviewSlaViolations}

## 🛠️ Validator Details
| Validator | Status | Execution Time | Warnings | Errors |
| :--- | :--- | :--- | :--- | :--- |
${results.map(res => `| ${res.name} | ${res.success ? '✅ Pass' : '❌ Fail'} | ${res.executionTimeMs} ms | ${res.warnings.length} | ${res.errors.length} |`).join('\n')}

---
*Generated by MAD Entertrainment Governance Automation Runner v${reportContent.validatorVersion || '1.2.0'}*
`;
      try {
        writeFileSync(summaryFile, summaryMarkdown, { encoding: 'utf8' });
      } catch (err) {
        console.error(`Failed to write GitHub Actions Step Summary to ${summaryFile}:`, err);
      }
    }

    return { success, failureReason };
  }
}
